name: Continuous Integration

on:
  pull_request:
  push:
    branches: [main]
    tags: ['**']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
            distribution: zulu
          - os: ubuntu-latest
            java: 21
            distribution: temurin
          - os: ubuntu-latest
            java: 25
            distribution: temurin
    runs-on: ${{ matrix.os }}
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Dfile.encoding=UTF-8 -Djava.security.manager=allow
      JVM_OPTS:  -Dfile.encoding=UTF-8 -Djava.security.manager=allow
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: "${{ matrix.distribution }}"
          java-version: "${{ matrix.java }}"
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Test
        shell: bash
        run: sbt -v clean +test +scripted
      - name: Ensure formatting
        shell: bash
        run: sbt -v clean scalafmtSbtCheck scalafmtCheckAll
